keybindings: null
behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  volume_percent: 59
  tick_rate_milliseconds: 60
  enable_text_emphasis: true
  show_loading_indicator: true
  enforce_wide_search_bar: true
  enable_global_song_count: true
  shuffle_enabled: true
  liked_icon: â™¥
  shuffle_icon: ğŸ”€
  repeat_track_icon: ğŸ”‚
  repeat_context_icon: ğŸ”
  playing_icon: â–¶
  paused_icon: â¸
  set_window_title: true
  visualizer_style: Equalizer
theme:
  active: 203, 216, 140
  banner: 208, 219, 142
  error_border: 221, 124, 76
  error_text: 192, 108, 67
  hint: 225, 196, 125
  hovered: 194, 168, 108
  inactive: 90, 93, 97
  playbar_background: 38, 38, 38
  playbar_progress: 175, 185, 121
  playbar_progress_text: 175, 185, 121
  playbar_text: 254, 255, 211
  selected: 175, 185, 121
  text: 254, 255, 211
  background: 20, 20, 20
  header: 254, 255, 211
  highlighted_lyrics: 0, 200, 200
